### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by aletournel** [Pluies/config-reloader-sidecar#1]
Hello Florent,

Thanks you for sharing this project publicly. It could be useful for us but we need to know on which license this repository is under. Could you explicitly add one ?

There is a well made guide for this on https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository. 

For exemple, one of the most used one is the MIT license (https://choosealicense.com/licenses/mit/).

Again thanks a lot

**Comment by Pluies** [comment]
Hey Adrien,
Thanks for flagging this up! I didn't realise this was missing a license!
I've [licensed this under the Apache license](https://github.com/Pluies/config-reloader-sidecar/commit/2fc4b7f02fd5f83b62fae52bc9041beb2ac5a5b7) as I'm more familiar with it than MIT, but it's a similar copyleft style license so hopefully this suits you :)
Cheers!
- Florent

**Comment by aletournel** [comment]
Hey again Florent, 

That was a very quick answer :+1:. Indeed, this suit me perfectly. I will then be able to use it to reload the config for a couple of pods inside kubernetes clusters at my company.

Thanks and cheers to you as well! :v: :smiley:
