### ISSUE TITLE
Adding a first tag

### ISSUE THREAD

**Issue by pporee** [Pluies/config-reloader-sidecar#2]
Hello Florent, 

Do you think it would be possible to create a first tag like a 1.0.0 version ? 

thanks for you work !
Pierre

**Comment by pporee** [comment]
Hello Florent, did you had time to have a look for this issue ? :)

**Comment by Pluies** [comment]
🙈 that totally slipped my mind, thank you for reminding me!
Tag created: https://github.com/Pluies/config-reloader-sidecar/releases/tag/v0.0.1
